import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { promisify } from "node:util";

import { releasePullRequestFreshnessViolations } from "../scripts/check-release-pr-freshness.mjs";

const execFileAsync = promisify(execFile);
const packageName = "@agent-teams/engineering-foundation";

async function git(cwd, ...args) {
  const { stdout } = await execFileAsync("git", args, { cwd, encoding: "utf8" });
  return stdout.trim();
}

function changeset(summary) {
  return '---\n"' + packageName + '": minor\n---\n\n' + summary + "\n";
}

function generatedRelease(version, summaries) {
  const entries = summaries
    .map(
      (summary, index) =>
        "- [#" +
        (index + 1) +
        "](https://example.invalid/pr/" +
        (index + 1) +
        ") - " +
        summary,
    )
    .join("\n\n");
  const heading = "## " + version;
  const changelogSection = heading + "\n\n### Minor Changes\n\n" + entries;
  return {
    changelog:
      "# " +
      packageName +
      "\n\n" +
      changelogSection +
      "\n\n## 1.0.0\n",
    body:
      "Generated by Changesets.\n\n# Releases\n" +
      changelogSection.replace(heading, "## " + packageName + "@" + version),
  };
}

async function createFixture() {
  const root = await mkdtemp(join(tmpdir(), "foundation-release-freshness-"));
  await mkdir(join(root, ".changeset"), { recursive: true });
  await mkdir(join(root, "packages", "engineering-foundation"), { recursive: true });
  await writeFile(
    join(root, "packages", "engineering-foundation", "package.json"),
    JSON.stringify({ name: packageName, version: "1.0.0" }),
  );
  await writeFile(
    join(root, "packages", "engineering-foundation", "CHANGELOG.md"),
    "# " + packageName + "\n\n## 1.0.0\n",
  );
  await writeFile(join(root, ".changeset", "alpha.md"), changeset("Alpha package change."));
  await git(root, "init", "-b", "main");
  await git(root, "config", "user.name", "Foundation Test");
  await git(root, "config", "user.email", "foundation-test@example.invalid");
  await git(root, "add", ".");
  await git(root, "commit", "-m", "main A");
  return { root, mainA: await git(root, "rev-parse", "HEAD") };
}

async function createRelease(root, baseRevision, version, summaries) {
  await git(root, "checkout", "--detach", baseRevision);
  await rm(join(root, ".changeset", "alpha.md"), { force: true });
  await rm(join(root, ".changeset", "beta.md"), { force: true });
  const generated = generatedRelease(version, summaries);
  await writeFile(
    join(root, "packages", "engineering-foundation", "package.json"),
    JSON.stringify({ name: packageName, version }),
  );
  await writeFile(
    join(root, "packages", "engineering-foundation", "CHANGELOG.md"),
    generated.changelog,
  );
  await git(root, "add", ".");
  await git(root, "commit", "-m", "release " + version);
  return { head: await git(root, "rev-parse", "HEAD"), body: generated.body };
}

function pullRequest(baseSha, headSha, body) {
  return {
    state: "open",
    headRef: "changeset-release/main",
    headSha,
    baseRef: "main",
    baseSha,
    body,
  };
}

async function violations(root, processedMainSha, currentMainSha, release, expectedHeadSha) {
  return releasePullRequestFreshnessViolations(
    {
      processedMainSha,
      currentMainSha,
      expectedHeadSha,
      pullRequest: pullRequest(processedMainSha, release.head, release.body),
    },
    { cwd: root },
  );
}

test("release evidence follows the latest processed main across a two-push race", async () => {
  const fixture = await createFixture();
  try {
    const releaseA = await createRelease(
      fixture.root,
      fixture.mainA,
      "1.1.0",
      ["Alpha package change."],
    );
    assert.deepEqual(
      await violations(
        fixture.root,
        fixture.mainA,
        fixture.mainA,
        releaseA,
        releaseA.head,
      ),
      [],
    );

    await git(fixture.root, "checkout", "--detach", fixture.mainA);
    await writeFile(join(fixture.root, ".changeset", "beta.md"), changeset("Beta package change."));
    await git(fixture.root, "add", ".");
    await git(fixture.root, "commit", "-m", "main B");
    const mainB = await git(fixture.root, "rev-parse", "HEAD");

    assert.match(
      (await violations(fixture.root, fixture.mainA, mainB, releaseA, releaseA.head)).join("\n"),
      /processed main is stale/u,
    );

    const incompleteReleaseB = await createRelease(
      fixture.root,
      mainB,
      "1.2.0",
      ["Alpha package change."],
    );
    assert.match(
      (
        await violations(
          fixture.root,
          mainB,
          mainB,
          incompleteReleaseB,
          incompleteReleaseB.head,
        )
      ).join("\n"),
      /missing the summary from \.changeset\/beta\.md/u,
    );

    const releaseB = await createRelease(
      fixture.root,
      mainB,
      "1.2.0",
      ["Alpha package change.", "Beta package change."],
    );
    assert.deepEqual(
      await violations(fixture.root, mainB, mainB, releaseB, releaseB.head),
      [],
    );
    assert.match(
      (
        await violations(
          fixture.root,
          mainB,
          mainB,
          releaseB,
          incompleteReleaseB.head,
        )
      ).join("\n"),
      /head changed during attestation/u,
    );
  } finally {
    await rm(fixture.root, { recursive: true, force: true });
  }
});
