export const FOUNDATION_SCHEMA_IDS = [
  "architecture-source-dependencies/v1",
  "contract-json-schema-release-baseline/v1",
  "contract-json-schema-releases/v1",
  "contract-protobuf-breaking-qualification/v1",
  "contract-protobuf-evolution-baseline/v1",
  "contract-protobuf-evolution/v1",
  "document-authoring-profile/v1",
  "document-command-envelope/v1",
  "document-command-envelope/v2",
  "document-intent/v1",
  "document-plan/v1",
  "document-receipt/v1",
  "documentation-local-references/v1",
  "foundation-config/v1",
  "foundation-check-report/v1",
  "foundation-transaction-envelope/v2",
  "foundation-transaction-envelope/v3",
  "governance-architecture-decision-baseline/v1",
  "governance-architecture-decisions/v1",
  "package-public-api-baseline/v1",
  "package-public-api-compatibility/v1",
  "quality-executable-specification-catalog/v1",
  "quality-executable-specifications/v1",
  "quality-suppression-governance/v1",
  "repository-agent-workflow/v1",
  "repository-security-baseline/v1",
  "scaffold-authority-evidence/v1",
  "scaffold-intent/v1",
  "scaffold-plan/v1",
  "scaffold-receipt/v1",
  "scaffold-recovery-journal/v1",
  "scaffold-target-catalog/v1",
  "scaffolding-config/v1",
  "workspace-dependency-declarations/v1"
] as const;

export type FoundationSchemaId = (typeof FOUNDATION_SCHEMA_IDS)[number];

export type FoundationSchemaCatalogId = FoundationSchemaId;
